// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin testAccDataSource

func TestAccDataSourceFmcIcmpv4_bulk(t *testing.T) {
	var checks []resource.TestCheckFunc
	checks = append(checks, resource.TestCheckResourceAttr("data.fmc_icmpv4_bulk.test", "bulk.0.id", ""))
	checks = append(checks, resource.TestCheckResourceAttr("data.fmc_icmpv4_bulk.test", "bulk.0.name", "icmpv4_obj"))
	checks = append(checks, resource.TestCheckResourceAttr("data.fmc_icmpv4_bulk.test", "bulk.0.icmp_type", "3"))
	checks = append(checks, resource.TestCheckResourceAttr("data.fmc_icmpv4_bulk.test", "bulk.0.code", "0"))
	checks = append(checks, resource.TestCheckResourceAttr("data.fmc_icmpv4_bulk.test", "bulk.0.description", "Test Description"))
	checks = append(checks, resource.TestCheckResourceAttr("data.fmc_icmpv4_bulk.test", "bulk.0.overridable", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.fmc_icmpv4_bulk.test", "bulk.0.parent_id", "icmpv4_obj_uuid"))
	checks = append(checks, resource.TestCheckResourceAttr("data.fmc_icmpv4_bulk.test", "bulk.0.parent_type", "ICMPV4Object"))
	checks = append(checks, resource.TestCheckResourceAttr("data.fmc_icmpv4_bulk.test", "bulk.0.target_id", "domain_uuid"))
	checks = append(checks, resource.TestCheckResourceAttr("data.fmc_icmpv4_bulk.test", "bulk.0.target_type", "Domain"))
	checks = append(checks, resource.TestCheckResourceAttr("data.fmc_icmpv4_bulk.test", "bulk.0.target_name", "Global \\ EUROPE"))
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccDataSourceFmcIcmpv4_bulkConfig(),
				Check:  resource.ComposeTestCheckFunc(checks...),
			},
		},
	})
}

// End of section. //template:end testAccDataSource

// Section below is generated&owned by "gen/generator.go". //template:begin testPrerequisites
// End of section. //template:end testPrerequisites

// Section below is generated&owned by "gen/generator.go". //template:begin testAccDataSourceConfig

func testAccDataSourceFmcIcmpv4_bulkConfig() string {
	config := `resource "fmc_icmpv4_bulk" "test" {` + "\n"
	config += `	bulk = [{` + "\n"
	config += `		id = ""` + "\n"
	config += `		name = "icmpv4_obj"` + "\n"
	config += `		icmp_type = "3"` + "\n"
	config += `		code = 0` + "\n"
	config += `		description = "Test Description"` + "\n"
	config += `		overridable = true` + "\n"
	config += `		parent_id = "icmpv4_obj_uuid"` + "\n"
	config += `		parent_type = "ICMPV4Object"` + "\n"
	config += `		target_id = "domain_uuid"` + "\n"
	config += `		target_type = "Domain"` + "\n"
	config += `		target_name = "Global \\ EUROPE"` + "\n"
	config += `	}]` + "\n"
	config += `}` + "\n"

	config += `
		data "fmc_icmpv4_bulk" "test" {
			id = fmc_icmpv4_bulk.test.id
		}
	`
	return config
}

// End of section. //template:end testAccDataSourceConfig
