// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"context"
	"fmt"
	"net/url"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/netascode/go-fmc"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin model

// Ensure the implementation satisfies the expected interfaces.
var (
	_ datasource.DataSource              = &Icmpv4_bulkDataSource{}
	_ datasource.DataSourceWithConfigure = &Icmpv4_bulkDataSource{}
)

func NewIcmpv4_bulkDataSource() datasource.DataSource {
	return &Icmpv4_bulkDataSource{}
}

type Icmpv4_bulkDataSource struct {
	client *fmc.Client
}

func (d *Icmpv4_bulkDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_icmpv4_bulk"
}

func (d *Icmpv4_bulkDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		// This description is used by the documentation generator and the language server.
		MarkdownDescription: "This data source can read the icmpv4_bulk.",

		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				MarkdownDescription: "The id of the object",
				Required:            true,
			},
			"domain": schema.StringAttribute{
				MarkdownDescription: "The name of the FMC domain",
				Optional:            true,
			},
			"bulk": schema.ListNestedAttribute{
				MarkdownDescription: "",
				Computed:            true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"id": schema.StringAttribute{
							MarkdownDescription: "UUID of the ICMPv4 Object",
							Computed:            true,
						},
						"name": schema.StringAttribute{
							MarkdownDescription: "The name of the ICMPv4 object (name should be same as parent if overriding)",
							Computed:            true,
						},
						"icmp_type": schema.StringAttribute{
							MarkdownDescription: "ICMP Type Number",
							Computed:            true,
						},
						"code": schema.Int64Attribute{
							MarkdownDescription: "ICMP Code",
							Computed:            true,
						},
						"description": schema.StringAttribute{
							MarkdownDescription: "Description for the ICMPv4 Object",
							Computed:            true,
						},
						"overridable": schema.BoolAttribute{
							MarkdownDescription: "Set if ICMPv4 Object is Overridable",
							Computed:            true,
						},
						"parent_id": schema.StringAttribute{
							MarkdownDescription: "Id of the rescource",
							Computed:            true,
						},
						"parent_type": schema.StringAttribute{
							MarkdownDescription: "Type of the resource",
							Computed:            true,
						},
						"target_id": schema.StringAttribute{
							MarkdownDescription: "Id of the rescource",
							Computed:            true,
						},
						"target_type": schema.StringAttribute{
							MarkdownDescription: "Type of the resource [Device/Domain]",
							Computed:            true,
						},
						"target_name": schema.StringAttribute{
							MarkdownDescription: "Name of the resource",
							Computed:            true,
						},
					},
				},
			},
		},
	}
}

func (d *Icmpv4_bulkDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	d.client = req.ProviderData.(*FmcProviderData).Client
}

// End of section. //template:end model

// Section below is generated&owned by "gen/generator.go". //template:begin read

func (d *Icmpv4_bulkDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config Icmpv4_bulk

	// Read config
	diags := req.Config.Get(ctx, &config)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Set request domain if provided
	reqMods := [](func(*fmc.Req)){}
	if !config.Domain.IsNull() && config.Domain.ValueString() != "" {
		reqMods = append(reqMods, fmc.DomainName(config.Domain.ValueString()))
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Beginning Read", config.Id.String()))

	res, err := d.client.Get(config.getPath()+"/"+url.QueryEscape(config.Id.ValueString()), reqMods...)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Failed to retrieve object, got error: %s", err))
		return
	}

	config.fromBody(ctx, res)

	tflog.Debug(ctx, fmt.Sprintf("%s: Read finished successfully", config.Id.ValueString()))

	diags = resp.State.Set(ctx, &config)
	resp.Diagnostics.Append(diags...)
}

// End of section. //template:end read
